spring:
    data:
        mongodb:
            host: localhost
            port: 27017
            database: mindmap
            username: user
            password: pass
    banner:
      location: banner.txt
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    info:
      enabled: true
